name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: Install NPM Dependencies
        uses: bahmutov/npm-install@v1.7.4

      - name: Compile Source Files
        run: npm run build

      - name: Publish
        run: |
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          npm version ${{ inputs.version }}
          npm publish
          git commit -am "Bump version to ${{ inputs.version }}"
          git push --tags https://osyrisrblx:${{ secrets.github_token }}@github.com/${{ github.repo }}.git HEAD:master
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
